### ISSUE TITLE
If no password is found gives error (I think)

### ISSUE THREAD

**Issue by mattgrubbs** [alfanhui/dmgCracker#1]
I must be doing something wrong.  The only output I get is "...ERROR: No more unchecked files...".  Does this mean no passwords were found?

Also in your readme you give the line "...No more than 8 should be used on a quad-core cpu or else performance will be degraded. eg. Python3 source.py -t 8 image.dmg"  when I run "Python3 source.py -t 8 image.dmg" I get "...source.py: error: no such option: -t"

Help??

**Comment by alfanhui** [comment]
So sorry, I only just saw this. Thank you for trying my program. It was a lost cause because I had not even considered anyone actually finding this and the program was hard coded to work with the filenames I had generated myself. The documentation did not reflect this. Sorry about that! Please however view the readme on the front page, I have updated it with a faster method which possibly supports GPU processes for faster password checks. 

Good luck with your cracking!
